CREATE TABLE groupe (idGroupe TEXT PRIMARY KEY);
CREATE TABLE timetable (idTT INTEGER PRIMARY KEY AUTOINCREMENT, dateDebut DATETIME, dateFin DATETIME, groupe TEXT, FOREIGN KEY(groupe) REFERENCES groupe(idGroupe));
CREATE TABLE lesson (idLesson INTEGER PRIMARY KEY AUTOINCREMENT, libelle TEXT, dateDebut DATETIME, dateFin DATETIME,intervenant TEXT,emplacement TEXT,idTT INTEGER NOT NULL, FOREIGN KEY(idTT) REFERENCES timetable(idTT));
CREATE TABLE message(idMessage INTEGER PRIMARY KEY AUTOINCREMENT, libelle TEXT, dateMessage DATETIME);